name: Build Windows Game

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create Project & Build
        run: |
          flutter create horouf_game --platforms windows
          Copy-Item -Path "main.dart" -Destination "horouf_game\lib\main.dart" -Force
          cd horouf_game
          
          flutter pub add window_manager
          flutter pub add file_picker
          flutter pub add google_fonts
         
          if (Test-Path "..\icon.png") {
            flutter pub add dev:flutter_launcher_icons
            Copy-Item -Path "..\icon.png" -Destination "icon.png" -Force
            echo "flutter_icons:" > flutter_launcher_icons.yaml
            echo "  image_path: `"icon.png`"" >> flutter_launcher_icons.yaml
            echo "  windows:" >> flutter_launcher_icons.yaml
            echo "    generate: true" >> flutter_launcher_icons.yaml
            flutter pub run flutter_launcher_icons -f flutter_launcher_icons.yaml
          }
          
          if (Test-Path "..\hacen.ttf") {
            mkdir assets\fonts
            Copy-Item -Path "..\hacen.ttf" -Destination "assets\fonts\hacen.ttf" -Force
            echo "  fonts:" >> pubspec.yaml
            echo "    - family: Hacen" >> pubspec.yaml
            echo "      fonts:" >> pubspec.yaml
            echo "        - asset: assets/fonts/hacen.ttf" >> pubspec.yaml
          }
          
          flutter build windows --release

      - name: Upload Windows Exe
        uses: actions/upload-artifact@v4
        with:
          name: Horouf_Game_Windows
          path: horouf_game\build\windows\x64\runner\Release\*
